/**
 * Shared context for client socket handler modules.
 * Mutable game/connection state is exposed via getters/setters so handlers
 * always read current values without re-binding on every state change.
 */

const STATE_ACCESSORS = [
	'myId',
	'gameState',
	'connectionState',
	'latency',
	'mySelectedDeck',
	'myInventory',
	'myOwnedCards',
	'myCurrency',
	'keyItemDefs',
	'enemyDisplayCatalog',
	'suspendedRunSummary',
	'currentLayoutSeed',
	'currentLayout',
	'hubLayout',
	'renderedSceneProfile',
	'debugScenarioResult',
	'debugGodmodeResult',
	'debugTimeScaleResult',
	'debugTimeScaleAllowed',
	'claimedCardRewardId',
	'currentCardChoices',
	'_prevDashX',
	'_prevDashZ',
	'keyItemCooldownUntilClient',
	'_lastReturnRewardsPreview',
	'_lastMagicStones',
	'_lastCurrency',
	'extractedLobbyOverlayActive',
	'lastUsedSlot',
	'activeLobbyTab',
	'pendingTradeOffer',
	'isReady',
	'lastEvolutionResult',
];

export function createSocketHandlerCtx(deps) {
	const ctx = {
		clearConnectWatchdog: deps.clearConnectWatchdog,
		startConnectWatchdog: deps.startConnectWatchdog,
		startHeartbeat: deps.startHeartbeat,
		stopHeartbeat: deps.stopHeartbeat,
		updateStatus: deps.updateStatus,
		statusEl: deps.statusEl,
		showLobbyBrowserError: deps.showLobbyBrowserError,
		disposeAllLootMeshes: deps.disposeAllLootMeshes,
		TOKEN_KEY: deps.TOKEN_KEY,
		setAuthToken: deps.setAuthToken,
		uiEl: deps.uiEl,
		giveUpBtnEl: deps.giveUpBtnEl,
		cardHandEl: deps.cardHandEl,
		hideCardHand: deps.hideCardHand,
		hideVariantCodex: deps.hideVariantCodex,
		setDeckStackVisible: deps.setDeckStackVisible,
		lobbyEl: deps.lobbyEl,
		setLobbyHudVisible: deps.setLobbyHudVisible,
		lobbyBrowserEl: deps.lobbyBrowserEl,
		lobbyBrowserStatusEl: deps.lobbyBrowserStatusEl,
		runSummaryOverlay: deps.runSummaryOverlay,
		showAuthOverlay: deps.showAuthOverlay,
		showLoginForm: deps.showLoginForm,
		rendererSetMyId: deps.rendererSetMyId,
		renderDeckEditor: deps.renderDeckEditor,
		setLoggedInStatus: deps.setLoggedInStatus,
		showAppToolbar: deps.showAppToolbar,
		showLobbyBrowser: deps.showLobbyBrowser,
		renderLobbyList: deps.renderLobbyList,
		applyLobbyJoinedData: deps.applyLobbyJoinedData,
		getBoothDebugHook: deps.getBoothDebugHook,
		launchBoothReadyUp: deps.launchBoothReadyUp,
		setGameStateRef: deps.setGameStateRef,
		STORAGE_KEY_PLAYER_ID: deps.STORAGE_KEY_PLAYER_ID,
		LAUNCH_BOOTH_ID: deps.LAUNCH_BOOTH_ID,
		hand: deps.hand,
		deck: deps.deck,
		cloneSuspendedRunSummary: deps.cloneSuspendedRunSummary,
		syncPassageLockColliders: deps.syncPassageLockColliders,
		syncPassageLockGates: deps.syncPassageLockGates,
		applyInRunDeckPayload: deps.applyInRunDeckPayload,
		renderHand: deps.renderHand,
		updateLevelSettingsBtnVisibility: deps.updateLevelSettingsBtnVisibility,
		isLevelSettingsOpen: deps.isLevelSettingsOpen,
		syncLevelSettingsRewards: deps.syncLevelSettingsRewards,
		syncLocalCollectionState: deps.syncLocalCollectionState,
		syncQuestCommsPhase: deps.syncQuestCommsPhase,
		clearQuestCommsLog: deps.clearQuestCommsLog,
		setQuestCommsUiVisible: deps.setQuestCommsUiVisible,
		flushPendingQuestDialogue: deps.flushPendingQuestDialogue,
		showExtractedLobbyOverlay: deps.showExtractedLobbyOverlay,
		returnToGuildLobby: deps.returnToGuildLobby,
		requestGiveUp: deps.requestGiveUp,
		showRunSummary: deps.showRunSummary,
		showLevelSettingsError: deps.showLevelSettingsError,
		renderSuspendedRunBanner: deps.renderSuspendedRunBanner,
		renderCardChoices: deps.renderCardChoices,
		removeRemotePlayerVisuals: deps.removeRemotePlayerVisuals,
		resolveRunSpawnPosition: deps.resolveRunSpawnPosition,
		initHand: deps.initHand,
		isSceneInitialized: deps.isSceneInitialized,
		rendererInitScene: deps.rendererInitScene,
		rebuildDungeonLayout: deps.rebuildDungeonLayout,
		setPlayerRotation: deps.setPlayerRotation,
		setWasDead: deps.setWasDead,
		rendererDisposeMeshMap: deps.rendererDisposeMeshMap,
		closeCharacterBooth: deps.closeCharacterBooth,
		alignAttackFacing: deps.alignAttackFacing,
		clearAllLockOnState: deps.clearAllLockOnState,
		slotCooldowns: deps.slotCooldowns,
		syncVanguardHud: deps.syncVanguardHud,
		showCardHand: deps.showCardHand,
		setDeployButtonVisible: deps.setDeployButtonVisible,
		clearSuspendedRunUi: deps.clearSuspendedRunUi,
		setGamePhase: deps.setGamePhase,
		updateHpBar: deps.updateHpBar,
		updateMsBar: deps.updateMsBar,
		updateDeckStats: deps.updateDeckStats,
		updateVanguardPortrait: deps.updateVanguardPortrait,
		updateCurrencyHud: deps.updateCurrencyHud,
		updateObjectiveHud: deps.updateObjectiveHud,
		updateBossEncounterHud: deps.updateBossEncounterHud,
		setInDesperation: deps.setInDesperation,
		setDesperationDrawPile: deps.setDesperationDrawPile,
		updateDeckVisuals: deps.updateDeckVisuals,
		syncDrawPileFromServer: deps.syncDrawPileFromServer,
		pruneLootPickupAttempts: deps.pruneLootPickupAttempts,
		isPlayerMoving: deps.isPlayerMoving,
		getPlayerPosition: deps.getPlayerPosition,
		setPlayerPosition: deps.setPlayerPosition,
		triggerDashVFX: deps.triggerDashVFX,
		getKeyItemCooldownRemainingMs: deps.getKeyItemCooldownRemainingMs,
		renderKeyItemHud: deps.renderKeyItemHud,
		updateKeyItemCooldownHud: deps.updateKeyItemCooldownHud,
		clearKeyItemCooldownHud: deps.clearKeyItemCooldownHud,
		getScene: deps.getScene,
		getMeshMaps: deps.getMeshMaps,
		playSound: deps.playSound,
		showCardErrorToast: deps.showCardErrorToast,
		handleQuestDialogue: deps.handleQuestDialogue,
		getCardSlotEl: deps.getCardSlotEl,
		THEME: deps.THEME,
		spawnAttackEffect: deps.spawnAttackEffect,
		spawnSummonEffect: deps.spawnSummonEffect,
		spawnMinionSummonInEffect: deps.spawnMinionSummonInEffect,
		spawnDivineGraceEffect: deps.spawnDivineGraceEffect,
		spawnPurifyingPulseEffect: deps.spawnPurifyingPulseEffect,
		spawnPurifyingPulseHealRing: deps.spawnPurifyingPulseHealRing,
		spawnCleanseBurstEffect: deps.spawnCleanseBurstEffect,
		spawnInfernoPillarEffect: deps.spawnInfernoPillarEffect,
		spawnEtherSiphonEffect: deps.spawnEtherSiphonEffect,
		spawnSpikeTrapEffect: deps.spawnSpikeTrapEffect,
		spawnVolatileExplosionEffect: deps.spawnVolatileExplosionEffect,
		spawnChainLightningEffect: deps.spawnChainLightningEffect,
		spawnLightningArc: deps.spawnLightningArc,
		flashMesh: deps.flashMesh,
		markCardHitEnemies: deps.markCardHitEnemies,
		spawnHitSpark: deps.spawnHitSpark,
		spawnParticleBurst: deps.spawnParticleBurst,
		spawnProjectileTrail: deps.spawnProjectileTrail,
		spawnImpactDecal: deps.spawnImpactDecal,
		spawnTelegraphRing: deps.spawnTelegraphRing,
		spawnMirrorWardShellEffect: deps.spawnMirrorWardShellEffect,
		dismissMirrorWardShellEffect: deps.dismissMirrorWardShellEffect,
		spawnMirrorWardReflectBurst: deps.spawnMirrorWardReflectBurst,
		applyHubPresence: deps.applyHubPresence,
		dispatchBoothAction: deps.dispatchBoothAction,
		updateRunDeckTotal: deps.updateRunDeckTotal,
		renderPhotonForge: deps.renderPhotonForge,
		renderCardShop: deps.renderCardShop,
		showShopError: deps.showShopError,
		showDeckError: deps.showDeckError,
		renderGuildMedic: deps.renderGuildMedic,
		MEDIC_HEAL_COST: deps.MEDIC_HEAL_COST,
		showMedicError: deps.showMedicError,
		renderKeyItemList: deps.renderKeyItemList,
		showKeyItemError: deps.showKeyItemError,
		triggerHealPulseVFX: deps.triggerHealPulseVFX,
		triggerMedicAllyHealVFX: deps.triggerMedicAllyHealVFX,
		triggerMedicEnergyBeadVFX: deps.triggerMedicEnergyBeadVFX,
		flashKeyItemIndicator: deps.flashKeyItemIndicator,
		triggerShieldVFX: deps.triggerShieldVFX,
		triggerSmokeVFX: deps.triggerSmokeVFX,
		triggerLootMagnetVFX: deps.triggerLootMagnetVFX,
		showForgeError: deps.showForgeError,
		playForgeAttuneAnimation: deps.playForgeAttuneAnimation,
		setUnlockedHats: deps.setUnlockedHats,
		rebuildBoothHatList: deps.rebuildBoothHatList,
		showBoothCosmeticError: deps.showBoothCosmeticError,
		setAccountCosmetic: deps.setAccountCosmetic,
		getAccountCosmetic: deps.getAccountCosmetic,
		formatCurrencyPrice: deps.formatCurrencyPrice,
		APPEARANCE_CHANGE_COST: deps.APPEARANCE_CHANGE_COST,
		isCharacterBoothOpen: deps.isCharacterBoothOpen,
		handleAppearanceChanged: deps.handleAppearanceChanged,
		handleAppearanceError: deps.handleAppearanceError,
		renderTradeOffer: deps.renderTradeOffer,
		renderTradeForm: deps.renderTradeForm,
		renderPlayerList: deps.renderPlayerList,
		applyQuestBoardFromPayload: deps.applyQuestBoardFromPayload,
		applyQuestLayoutFromServer: deps.applyQuestLayoutFromServer,
		showQuestError: deps.showQuestError,
		showQuestDialogueToast: deps.showQuestDialogueToast,
		applyDebugTimeScale: deps.applyDebugTimeScale,
	};

	for (const key of STATE_ACCESSORS) {
		Object.defineProperty(ctx, key, {
			get: () => deps.state[key],
			set: (v) => { deps.state[key] = v; },
			enumerable: true,
		});
	}

	return ctx;
}
