/**
 * Shared context for client socket handler modules.
 * Mutable game/connection state is exposed via getters/setters so handlers
 * always read current values without re-binding on every state change.
 */

const STATE_ACCESSORS = [
	'myId',
	'gameState',
	'connectionState',
	'latency',
	'mySelectedDeck',
	'myInventory',
	'myOwnedCards',
	'keyItemDefs',
	'enemyDisplayCatalog',
	'suspendedRunSummary',
	'currentLayoutSeed',
	'currentLayout',
	'hubLayout',
	'debugGodmodeResult',
	'_prevDashX',
	'_prevDashZ',
	'keyItemCooldownUntilClient',
	'_lastReturnRewardsPreview',
	'_lastMagicStones',
	'extractedLobbyOverlayActive',
];

export function createSocketHandlerCtx(deps) {
	const ctx = {
		clearConnectWatchdog: deps.clearConnectWatchdog,
		startConnectWatchdog: deps.startConnectWatchdog,
		startHeartbeat: deps.startHeartbeat,
		stopHeartbeat: deps.stopHeartbeat,
		updateStatus: deps.updateStatus,
		showLobbyBrowserError: deps.showLobbyBrowserError,
		disposeAllLootMeshes: deps.disposeAllLootMeshes,
		TOKEN_KEY: deps.TOKEN_KEY,
		setAuthToken: deps.setAuthToken,
		uiEl: deps.uiEl,
		cardHandEl: deps.cardHandEl,
		hideCardHand: deps.hideCardHand,
		hideVariantCodex: deps.hideVariantCodex,
		setDeckStackVisible: deps.setDeckStackVisible,
		lobbyEl: deps.lobbyEl,
		setLobbyHudVisible: deps.setLobbyHudVisible,
		lobbyBrowserEl: deps.lobbyBrowserEl,
		lobbyBrowserStatusEl: deps.lobbyBrowserStatusEl,
		runSummaryOverlay: deps.runSummaryOverlay,
		showAuthOverlay: deps.showAuthOverlay,
		showLoginForm: deps.showLoginForm,
		rendererSetMyId: deps.rendererSetMyId,
		renderDeckEditor: deps.renderDeckEditor,
		setLoggedInStatus: deps.setLoggedInStatus,
		showAppToolbar: deps.showAppToolbar,
		showLobbyBrowser: deps.showLobbyBrowser,
		renderLobbyList: deps.renderLobbyList,
		applyLobbyJoinedData: deps.applyLobbyJoinedData,
		getBoothDebugHook: deps.getBoothDebugHook,
		launchBoothReadyUp: deps.launchBoothReadyUp,
		setGameStateRef: deps.setGameStateRef,
		STORAGE_KEY_PLAYER_ID: deps.STORAGE_KEY_PLAYER_ID,
		LAUNCH_BOOTH_ID: deps.LAUNCH_BOOTH_ID,
		hand: deps.hand,
		deck: deps.deck,
		cloneSuspendedRunSummary: deps.cloneSuspendedRunSummary,
		syncPassageLockColliders: deps.syncPassageLockColliders,
		syncPassageLockGates: deps.syncPassageLockGates,
		applyInRunDeckPayload: deps.applyInRunDeckPayload,
		renderHand: deps.renderHand,
		updateLevelSettingsBtnVisibility: deps.updateLevelSettingsBtnVisibility,
		isLevelSettingsOpen: deps.isLevelSettingsOpen,
		syncLevelSettingsRewards: deps.syncLevelSettingsRewards,
		syncLocalCollectionState: deps.syncLocalCollectionState,
		syncQuestCommsPhase: deps.syncQuestCommsPhase,
		clearQuestCommsLog: deps.clearQuestCommsLog,
		setQuestCommsUiVisible: deps.setQuestCommsUiVisible,
		flushPendingQuestDialogue: deps.flushPendingQuestDialogue,
		showExtractedLobbyOverlay: deps.showExtractedLobbyOverlay,
		returnToGuildLobby: deps.returnToGuildLobby,
		syncVanguardHud: deps.syncVanguardHud,
		showCardHand: deps.showCardHand,
		setDeployButtonVisible: deps.setDeployButtonVisible,
		clearSuspendedRunUi: deps.clearSuspendedRunUi,
		setGamePhase: deps.setGamePhase,
		updateHpBar: deps.updateHpBar,
		updateMsBar: deps.updateMsBar,
		updateDeckStats: deps.updateDeckStats,
		updateVanguardPortrait: deps.updateVanguardPortrait,
		updateCurrencyHud: deps.updateCurrencyHud,
		updateObjectiveHud: deps.updateObjectiveHud,
		updateBossEncounterHud: deps.updateBossEncounterHud,
		setInDesperation: deps.setInDesperation,
		setDesperationDrawPile: deps.setDesperationDrawPile,
		updateDeckVisuals: deps.updateDeckVisuals,
		syncDrawPileFromServer: deps.syncDrawPileFromServer,
		pruneLootPickupAttempts: deps.pruneLootPickupAttempts,
		isPlayerMoving: deps.isPlayerMoving,
		getPlayerPosition: deps.getPlayerPosition,
		setPlayerPosition: deps.setPlayerPosition,
		triggerDashVFX: deps.triggerDashVFX,
		getKeyItemCooldownRemainingMs: deps.getKeyItemCooldownRemainingMs,
		renderKeyItemHud: deps.renderKeyItemHud,
		updateKeyItemCooldownHud: deps.updateKeyItemCooldownHud,
		clearKeyItemCooldownHud: deps.clearKeyItemCooldownHud,
	};

	for (const key of STATE_ACCESSORS) {
		Object.defineProperty(ctx, key, {
			get: () => deps.state[key],
			set: (v) => { deps.state[key] = v; },
			enumerable: true,
		});
	}

	return ctx;
}
