/** Ember Descent / fire-cavern Tier I preset — ticket 373 playthrough validation. */
export default {
	findingsTitle: 'Fire level validation findings',
	questId: 'ember_descent',
	questTier: 1,
	objectiveType: 'defeat_enemies',
	deployScenario: 'fire-cavern',
	layoutProfile: 'fire-cavern',
	lobbyName: 'Fire Level Validation',
	nearAddsScenario: 'ember-descent-near-adds',
	emberBurnScenario: 'ember-descent-ember-wraith-burn',
	lastEnemyScenario: 'ember-descent-last-enemy',
	cardMechanicsScenarios: {
		burn: 'fireball-ready',
		mutualExclusion: 'status-mutual-exclusion-ready',
		cleanse: 'purifying-pulse-ready',
		windup: 'magma-windup-ready',
	},
	objectiveCompleteScreenshot: '06-objective-complete',
	victoryScreenshot: '07-victory',
	telepipeScenario: 'fire-telepipe-ready',
	telepipeBeforeScreenshot: '08-telepipe-before',
	telepipeAfterScreenshot: '09-telepipe-after',
	addsTimeoutMs: 90000,
	bossDefeatTimeoutMs: 180000,
	victoryTimeoutMs: 30000,
};
