/** Frost Crossing / ice-cavern Tier I preset — ticket 372 playthrough validation. */
export default {
	findingsTitle: 'Ice level validation findings',
	questId: 'frost_crossing',
	questTier: 1,
	objectiveType: 'defeat_enemies',
	deployScenario: 'frost-crossing-tier-1',
	layoutProfile: 'ice-cavern',
	lobbyName: 'Ice Level Validation',
	nearAddsScenario: null,
	slipperyFloorScenario: null,
	surfaceTransitionScenario: null,
	glacialSlowScenario: null,
	lastEnemyScenario: null,
	cardMechanicsScenarios: {},
	telepipeScenario: null,
	objectiveCompleteScreenshot: '07-objective-complete',
	victoryScreenshot: '08-victory',
	telepipeBeforeScreenshot: '09-telepipe-before',
	telepipeAfterScreenshot: '10-telepipe-after',
	addsTimeoutMs: 90000,
	bossDefeatTimeoutMs: 180000,
	victoryTimeoutMs: 30000,
};
