/** Frost Crossing / ice-cavern Tier I preset — ticket 372 playthrough validation. */
export default {
	findingsTitle: 'Ice level validation findings',
	bossSpawnLabel: 'permafrost_warden (Permafrost Warden)',
	questId: 'frost_crossing',
	questTier: 1,
	objectiveType: 'stage_boss',
	bossType: 'permafrost_warden',
	deployScenario: 'frost-crossing-tier-1',
	layoutProfile: 'ice-cavern',
	lobbyName: 'Ice Level Validation',
	nearAddsScenario: 'frost-crossing-near-adds',
	bossApproachScenario: 'frost-crossing-boss-approach',
	encounterTriggerScenario: 'frost-crossing-encounter-trigger',
	bossLowHpScenario: 'frost-crossing-boss-low-hp',
	slipperyFloorScenario: 'slippery-floor-lab',
	surfaceTransitionScenario: 'frost-crossing-surface-transition',
	glacialSlowScenario: 'frost-crossing-glacial-thrower-slow',
	cardMechanicsScenarios: {
		burn: 'fireball-ready',
		mutualExclusion: 'status-mutual-exclusion-ready',
		cleanse: 'purifying-pulse-ready',
		windup: 'magma-windup-ready',
	},
	midCombatScreenshot: '04-mid-combat',
	bossDormantScreenshot: '05-boss-dormant',
	bossActiveScreenshot: '06-boss-active',
	glacialSlowScreenshot: '07-glacial-slow',
	cardBurnScreenshot: '08-card-burn',
	bossDefeatedScreenshot: '09-boss-defeated',
	victoryScreenshot: '10-victory',
	telepipeScenario: 'frost-crossing-telepipe-ready',
	telepipeBeforeScreenshot: '11-telepipe-before',
	telepipeAfterScreenshot: '12-telepipe-after',
	addsTimeoutMs: 90000,
	bossDefeatTimeoutMs: 180000,
	victoryTimeoutMs: 30000,
};
